base_lr: 0.05
coslr: false
coslrwarmup: true
criterions:
  PerformanceLoss:
    def_file: ./loss/REOT.py
    lamb: 0.759333629819388
    loss_params:
      freq_path: ./cls_freq/CIFAR-10-LT_IMBA200.json
    optim_params: null
    t1: 500
    t2: 462
    t3: 650
    weight: 1.0
endlr: 0.0
last: false
memory:
  centroids: false
  init_centroids: false
model_dir: null
networks:
  classifier:
    def_file: ./models/DotProductClassifier.py
    optim_params:
      lr: 0.1
      momentum: 0.9
      weight_decay: 0.0005
    params:
      feat_dim: 64
      num_classes: 10
  feat_model:
    def_file: ./models/ResNet32Feature.py
    fix: false
    optim_params:
      lr: 0.05
      momentum: 0.9
      weight_decay: 0.0005
    params: {}
shuffle: false
training_opt:
  backbone: resnet32
  batch_size: 512
  cifar_imb_ratio: 200
  dataset: CIFAR10_LT
  display_step: 10
  feature_dim: 64
  log_dir: ./logs/cifar10/reot
  num_classes: 10
  num_iterations: 15000
  num_workers: 4
  open_threshold: 0.1
  sampler: null
  scheduler_params:
    gamma: 0.1
    step_size: 3
  sub_dir: models
warmup_iterations: 800
warmup_lr: 0.1
