base_lr: 0.05
coslr: true
criterions:
  PerformanceLoss:
    def_file: ./loss/REOT.py
    lamb: 0.74
    loss_params: {freq_path: ./cls_freq/ImageNet-LT_RESNET10.json}
    optim_params: null
    t1: 75
    t2: 78
    t3: 90
    weight: 1.0
endlr: 0.0
last: false
memory: {centroids: false, init_centroids: false}
model_dir: null
networks:
  classifier:
    def_file: ./models/DotProductClassifier.py
    optim_params: {lr: 0.2, momentum: 0.9, weight_decay: 0.0005}
    params: {dataset: ImageNet_LT, feat_dim: 512, log_dir: ./logs/ImageNet_LT/clslearn/ours_2_resnet10,
      num_classes: 1000, stage1_weights: false}
  feat_model:
    def_file: ./models/ResNet10Feature.py
    fix: false
    optim_params: {lr: 0.2, momentum: 0.9, weight_decay: 0.0005}
    params: {dataset: ImageNet_LT, dropout: null, log_dir: ./logs/ImageNet_LT/clslearn/ours_2_resnet10,
      stage1_weights: false, use_fc: false, use_selfatt: false}
shuffle: false
training_opt:
  backbone: resnet10
  batch_size: 512
  dataset: ImageNet_LT
  display_step: 10
  feature_dim: 512
  log_dir: ./logs/rebuttal_ImageNet/clslearn/softmax_resnet10_cbs
  log_root: /logs/ImageNet_LT
  num_classes: 1000
  num_epochs: 110
  num_workers: 12
  open_threshold: 0.1
  sampler: null
  scheduler_params: {gamma: 0.1, step_size: 3}
  stage: ours_2_resnet10
  sub_dir: models
